# Generated by Django 4.2.5 on 2023-09-21 08:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product_app', '0002_alter_category_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='like',
            field=models.ManyToManyField(blank=True, null=True, related_name='product', to=settings.AUTH_USER_MODEL),
        ),
    ]
