# Generated by Django 4.2.5 on 2023-09-26 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0005_commentproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('percent', models.PositiveSmallIntegerField()),
                ('product', models.ManyToManyField(related_name='offer', to='product_app.product')),
            ],
        ),
    ]
