# Generated by Django 4.2.5 on 2023-09-25 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_app', '0005_couponcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couponcode',
            name='name',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
