# Generated by Django 4.2.5 on 2023-09-25 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_app', '0006_alter_couponcode_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='couponcode',
            old_name='is_publish',
            new_name='active',
        ),
        migrations.RenameField(
            model_name='couponcode',
            old_name='created_at',
            new_name='valid_from',
        ),
        migrations.AddField(
            model_name='couponcode',
            name='valid_to',
            field=models.DateTimeField(null=True),
        ),
    ]
