# Generated by Django 4.2.5 on 2023-09-25 12:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cart_app', '0007_rename_is_publish_couponcode_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couponcode',
            name='valid_from',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
