# Generated by Django 4.2.5 on 2023-09-25 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_app', '0008_alter_couponcode_valid_from'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couponcode',
            name='valid_to',
            field=models.DateTimeField(),
        ),
    ]
