# Generated by Django 4.2.5 on 2023-09-26 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_app', '0009_alter_couponcode_valid_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
