# Generated by Django 4.2.5 on 2023-09-26 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_app', '0010_orderitem_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='address',
        ),
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
