# Generated by Django 4.2.5 on 2023-09-21 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0004_addressuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='addressuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='addressuser',
            name='country',
            field=models.CharField(choices=[('Iran', 'Iran'), ('Aragh', 'Aragh')], max_length=30),
        ),
    ]
