# Generated by Django 4.2.5 on 2023-09-21 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0005_addressuser_created_at_alter_addressuser_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addressuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
