# Generated by Django 4.2.5 on 2023-09-21 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0006_alter_addressuser_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='addressuser',
            name='state',
            field=models.CharField(max_length=70, null=True),
        ),
    ]
