# Generated by Django 4.2.5 on 2023-09-21 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0007_addressuser_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addressuser',
            name='state',
            field=models.CharField(max_length=70),
        ),
    ]
