# Generated by Django 4.2.5 on 2023-09-25 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0009_alter_addressuser_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='addressuser',
            name='email',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='addressuser',
            name='phone',
            field=models.CharField(max_length=11, null=True),
        ),
    ]
