# Generated by Django 4.2.5 on 2023-09-26 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0011_alter_addressuser_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailForNewLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
    ]
