# Generated by Django 4.2.5 on 2023-09-26 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0012_emailfornewletter'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrimaryUserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=11)),
                ('address', models.TextField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('url_instagram', models.CharField(max_length=50)),
                ('url_linkedin', models.CharField(max_length=50)),
                ('url_facebook', models.CharField(max_length=50)),
                ('url_twitter', models.CharField(max_length=50)),
            ],
        ),
    ]
